Repository boostcampwm-2022/android05-MoGakRun, pull requests merged in 2022-11, with the labels that each got.

#2 :wrench: Timber, Leakcanary 라이브러리 세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/whyranoid/mogakrun/MogakrunApplication.kt
  app/src/main/java/com/whyranoid/mogakrun/util/TimberDebugTree.kt
  build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/MainActivity.kt
Labels: 승민

#3 PR 템플릿 수정, CI에 구글 서비스 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/mogakrunci.yml
Labels: 현수

#4 파이어베이스 연동
  build.gradle
  data/build.gradle
Labels: 현수

#5 Base Components 추가, 데이터 바인딩 설정
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/base/BaseActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/base/BaseFragment.kt
Labels: 병희

#6 Base Components 추가, databinding 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/mogakrunci.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/whyranoid/mogakrun/MogakrunApplication.kt
  app/src/main/java/com/whyranoid/mogakrun/util/TimberDebugTree.kt
  build.gradle
  data/build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/MainActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/base/BaseActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/base/BaseFragment.kt
Labels: 병희, 승민, 용한, 현수

#7 브랜드 색상 설정, 폰트 추가 및 텍스트 스타일 지정
  presentation/src/main/res/font/nanum_square_round_bold.otf
  presentation/src/main/res/font/nanum_square_round_extra_bold.otf
  presentation/src/main/res/font/nanum_square_round_light.otf
  presentation/src/main/res/font/nanum_square_round_regular.otf
  presentation/src/main/res/values-night/colors.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: 병희, 승민, 용한, 현수

#9 domain layer의 UseCase 작성
  domain/src/main/java/com/whyranoid/domain/usecase/CreatePostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/DeletePostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetCurrentRunnerCountUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetGroupNotificationsUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyGroupListUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetPagingPostsUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetRunningHistoryUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetUnpostedRunningHistoryUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/JoinGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/SaveRunningHistoryUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/StartRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/UpdateGroupInfoUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/UpdatePostRepository.kt
Labels: 병희, 승민, 용한, 현수

#10 account 레포지토리, 유즈케이스 작성
  domain/src/main/java/com/whyranoid/domain/repository/AccountRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CreatePostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyGroupListUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetNicknameUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetProfileUrlUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetUidUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetUserUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/JoinGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/StartRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/UpdateNicknameUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/UpdateProfileUrlUseCase.kt
Labels: 병희, 승민, 용한, 현수

#11 러닝탭 화면 구현 (현재 러너 카운트 받아오기)
  app/build.gradle
  app/src/main/java/com/whyranoid/mogakrun/MogakrunApplication.kt
  build.gradle
  data/build.gradle
  data/src/main/java/com/whyranoid/data/di/NetworkModule.kt
  data/src/main/java/com/whyranoid/data/di/running/RunningDataSource.kt
  data/src/main/java/com/whyranoid/data/di/running/RunningDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/di/running/RunningModule.kt
  data/src/main/java/com/whyranoid/data/running/RunningRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetRunnerCountUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/MainActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/base/BaseFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartViewModel.kt
  presentation/src/main/res/drawable/thumbnail_src_small.png
  presentation/src/main/res/layout/fragment_running_start.xml
  presentation/src/main/res/raw/runing_tab_animation.json
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 병희, 용한

#12 data layer의 GroupRepositoryImpl 일부 구현
  build.gradle
  data/src/main/java/com/whyranoid/data/constant/CollectionId.kt
  data/src/main/java/com/whyranoid/data/constant/Exceptions.kt
  data/src/main/java/com/whyranoid/data/constant/FieldId.kt
  data/src/main/java/com/whyranoid/data/group/GroupDataSource.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/model/GroupInfoResponse.kt
  data/src/main/java/com/whyranoid/data/model/UserResponse.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSource.kt
  domain/src/main/java/com/whyranoid/domain/model/Rule.kt
Labels: 현수

#16 운동 시작 및 종료 알림들을 받아오는 Flow구현, GroupRepository에 exitGroup 추가
  data/src/main/java/com/whyranoid/data/constant/FieldId.kt
  data/src/main/java/com/whyranoid/data/group/GroupDataSource.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSource.kt
  data/src/main/java/com/whyranoid/data/model/GroupNotificationResponse.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
Labels: 현수

#20 커뮤니티 탭 기본 틀 구현
  build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityCategory.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityCategoryAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
  presentation/src/main/res/layout/fragment_community.xml
  presentation/src/main/res/layout/fragment_community_item.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수

#19 파이어베이스 구글 로그인 로직 구현 및 데이터 스토어에 저장 작업 진행 중
  app/src/main/AndroidManifest.xml
  build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/SignInActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/SplashActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/SettingFragment.kt
  presentation/src/main/res/layout/activity_sign_in.xml
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/layout/fragment_running_start.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
  signin/build.gradle
  signin/src/main/java/com/whyranoid/DataStoreModule.kt
  signin/src/main/java/com/whyranoid/SaveLogInUserInfoUseCase.kt
  signin/src/main/java/com/whyranoid/SignInDataSource.kt
  signin/src/main/java/com/whyranoid/SignInRepository.kt
  signin/src/main/java/com/whyranoid/SignInRepositoryImpl.kt
  signin/src/main/java/com/whyranoid/SignInViewModel.kt
  signin/src/main/java/com/whyranoid/signin/SignInActivity.kt
  signin/src/main/res/layout/activity_sign_in.xml
  signin/src/main/res/values/strings.xml
Labels: 리뷰요청, 승민

#24 네트워크 연결 상태 관리 모듈 추가 및 Running Tab 완성
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/whyranoid/data/account/AccountRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/di/AccountModule.kt
  data/src/main/java/com/whyranoid/data/di/GroupModule.kt
  data/src/main/java/com/whyranoid/data/di/RunningModule.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSource.kt
  data/src/main/java/com/whyranoid/data/running/RunningDataSource.kt
  data/src/main/java/com/whyranoid/data/running/RunningDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/running/RunningRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/StartRunningUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/whyranoid/presentation/di/NetworkConnectionModule.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/util/BindingAdapters.kt
  presentation/src/main/java/com/whyranoid/presentation/util/Extensions.kt
  presentation/src/main/java/com/whyranoid/presentation/util/networkconnection/NetworkConnectionState.kt
  presentation/src/main/java/com/whyranoid/presentation/util/networkconnection/NetworkState.kt
  presentation/src/main/res/layout/activity_running.xml
  presentation/src/main/res/layout/fragment_running_start.xml
  presentation/src/main/res/layout/network_conntection_alert.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 병희, 용한

#25 datastore에 최초 로그인한 유저의 uid, email, nickname, profile 이미지 uri 저장, 마이런, 설정 페이지 레이아웃 작성
  app/src/main/AndroidManifest.xml
  build.gradle
  presentation/build.gradle
  presentation/src/main/res/drawable/my_run_edit_nick_name.xml
  presentation/src/main/res/drawable/my_run_tool_bar_setting.xml
  presentation/src/main/res/drawable/navigation_back_button.xml
  presentation/src/main/res/layout/fragment_my_run.xml
  presentation/src/main/res/layout/fragment_setting.xml
  presentation/src/main/res/layout/item_calendar_day.xml
  presentation/src/main/res/menu/my_run_setting_menu.xml
  presentation/src/main/res/values/strings.xml
  settings.gradle
  signin/build.gradle
  signin/src/main/java/com/whyranoid/SaveLogInUserInfoUseCase.kt
  signin/src/main/java/com/whyranoid/SignInDataSource.kt
  signin/src/main/java/com/whyranoid/SignInDataSourceImpl.kt
  signin/src/main/java/com/whyranoid/SignInModule.kt
  signin/src/main/java/com/whyranoid/SignInRepository.kt
  signin/src/main/java/com/whyranoid/SignInRepositoryImpl.kt
  signin/src/main/java/com/whyranoid/SignInUserInfo.kt
  signin/src/main/java/com/whyranoid/SignInViewModel.kt
  signin/src/main/java/com/whyranoid/signin/SignInActivity.kt
Labels: 리뷰완료, 승민

#30 그룹 생성하기 페이지 구현 + 컴포즈로 커스텀 Dialog 구현
  data/src/main/java/com/whyranoid/data/group/GroupDataSource.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CreateGroupUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/CreateGroupFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/CreateGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/compose/DropDownMenu.kt
  presentation/src/main/java/com/whyranoid/presentation/compose/RulePicker.kt
  presentation/src/main/res/drawable/done_outline_icon.xml
  presentation/src/main/res/drawable/done_solid_icon.xml
  presentation/src/main/res/drawable/plus_button.xml
  presentation/src/main/res/layout/fragment_create_group.xml
  presentation/src/main/res/menu/create_group_menu.xml
  presentation/src/main/res/menu/my_group_menu.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수

#35 그룹 상세보기 페이지 구현
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupNotificationAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupSettingDialog.kt
  presentation/src/main/java/com/whyranoid/presentation/model/GroupInfoUiModel.kt
  presentation/src/main/java/com/whyranoid/presentation/model/RuleUiModel.kt
  presentation/src/main/java/com/whyranoid/presentation/model/UserUiModel.kt
  presentation/src/main/java/com/whyranoid/presentation/util/BindingAdapters.kt
  presentation/src/main/res/layout/fragment_group_detail.xml
  presentation/src/main/res/layout/group_setting_dialog.xml
  presentation/src/main/res/layout/my_finish_notification_item.xml
  presentation/src/main/res/layout/my_start_notification_item.xml
  presentation/src/main/res/layout/other_finish_notification_item.xml
  presentation/src/main/res/layout/other_start_notification_item.xml
  presentation/src/main/res/menu/group_detail_menu.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수

#37 Room DB 구현 및 나의 운동기록 가져와서 화면에 띄우는 로직 구현, 바텀 네비게이션 구현
  build.gradle
  data/build.gradle
  data/src/main/java/com/whyranoid/data/account/AccountDataSource.kt
  data/src/main/java/com/whyranoid/data/account/AccountDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/AccountRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryDao.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryEntity.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataBase.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSource.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/di/AccountModule.kt
  data/src/main/java/com/whyranoid/data/di/DataBaseModule.kt
  domain/src/main/java/com/whyranoid/domain/repository/AccountRepository.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunningHistoryRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetRunningHistoryUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetUidUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/JoinGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/StartRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/UpdateNicknameUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/MainActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunningHistoryAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunningHistoryDiffCallback.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/RunningHistoryUiModel.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/bottom_navigation_bar.xml
  presentation/src/main/res/layout/fragment_my_run.xml
  presentation/src/main/res/layout/fragment_running_start.xml
  presentation/src/main/res/layout/fragment_setting.xml
  presentation/src/main/res/layout/item_running_history.xml
  presentation/src/main/res/menu/bottom_navigation_menu.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 승민

#43 간단한 리팩터링, UiState 추가, 커스텀 Exception 추가
  data/src/main/java/com/whyranoid/data/group/GroupDataSource.kt
  domain/src/main/java/com/whyranoid/domain/model/MoGakRunException.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/MyGroupAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/CreateGroupFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupNotificationAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/model/UiState.kt
  presentation/src/main/res/layout/my_group_item.xml
Labels: 리뷰요청, 병희, 승민, 용한, 현수

#45 현재 연결된 계정 표시 구현, 로그아웃/회원탈퇴 로직 구현, 캘린더 뷰 구현
  build.gradle
  data/build.gradle
  data/src/main/java/com/whyranoid/data/account/AccountDataSource.kt
  data/src/main/java/com/whyranoid/data/account/AccountDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/AccountRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryDao.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryEntity.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/di/RunningHistoryDataBaseModule.kt
  data/src/main/java/com/whyranoid/data/di/UserDataBaseModule.kt
  domain/src/main/java/com/whyranoid/domain/repository/AccountRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetEmailUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetNicknameUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/SignOutUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/WithDrawalUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/model/RunningHistoryUiModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/CalendarDayBinder.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunningHistoryAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunningHistoryDiffCallback.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/SettingFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/SettingViewModel.kt
  presentation/src/main/res/drawable/calendar_kong.png
  presentation/src/main/res/layout/fragment_my_run.xml
  presentation/src/main/res/layout/fragment_setting.xml
  presentation/src/main/res/layout/item_calendar_day.xml
  presentation/src/main/res/layout/item_running_history.xml
Labels: 리뷰요청, 승민, 이슈

#38 러닝 화면 구현
  .github/workflows/mogakrunci.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/whyranoid/mogakrun/MogakrunApplication.kt
  build.gradle
  data/src/main/java/com/whyranoid/data/di/RunningModule.kt
  data/src/main/java/com/whyranoid/data/running/RunnerDataSource.kt
  data/src/main/java/com/whyranoid/data/running/RunnerDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/running/RunnerRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunnerRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetRunnerCountUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/StartRunningUseCase.kt
  gradle.properties
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/whyranoid/presentation/base/BaseActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningPosition.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningRepository.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningWorker.kt
  presentation/src/main/java/com/whyranoid/presentation/running/WorkManagerInitializer.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/util/BindingAdapters.kt
  presentation/src/main/java/com/whyranoid/presentation/util/Extensions.kt
  presentation/src/main/java/com/whyranoid/presentation/util/gpsstate/GPSState.kt
  presentation/src/main/java/com/whyranoid/presentation/util/networkconnection/NetworkConnectionStateHolder.kt
  presentation/src/main/res/drawable/kong.xml
  presentation/src/main/res/layout/activity_running.xml
  presentation/src/main/res/values/strings.xml
  settings.gradle
Labels: 리뷰요청, 병희, 용한

#47 코드 리뷰 피드백 반영 및 운동 기록 가져오기 레이아웃 및 기능 구현
  data/src/main/java/com/whyranoid/data/account/AccountDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSource.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/di/UserDataBaseModule.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunningHistoryRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetRunningHistoryUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CreateRunningPostFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/SelectRunningHistoryFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/SelectRunningHistoryViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/model/RunningHistoryUiModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/CalendarDayBinder.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunningHistoryAdapter.kt
  presentation/src/main/res/layout/fragment_create_running_post.xml
  presentation/src/main/res/layout/fragment_select_running_history.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 승민

#51 홍보 글 작성 기능 구현, 홍보 글 불러오기 기능 구현
  data/src/main/java/com/whyranoid/data/Post/PostDataSource.kt
  data/src/main/java/com/whyranoid/data/Post/PostRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/model/PostResponse.kt
  domain/src/main/java/com/whyranoid/domain/repository/PostRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CreateRecruitPostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetPostsUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/PostAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
  presentation/src/main/res/layout/item_recruit_post.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수

#54 그룹 생성 및 수정 시 그룹 이름 중복확인 기능 추가, FinishNotifiacation관련 수정
  data/src/main/java/com/whyranoid/data/Post/PostDataSource.kt
  data/src/main/java/com/whyranoid/data/constant/CollectionId.kt
  data/src/main/java/com/whyranoid/data/group/GroupDataSource.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSource.kt
  data/src/main/java/com/whyranoid/data/model/GroupNotificationResponse.kt
  domain/src/main/java/com/whyranoid/domain/model/RunningHistory.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CheckIsDuplicatedGroupNameUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/EditGroupFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/EditGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/Event.kt
  presentation/src/main/res/layout/fragment_create_group.xml
  presentation/src/main/res/layout/fragment_edit_group.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수
