Repository boostcampwm-2022/android05-MoGakRun, pull requests merged in 2022-12, with the labels that each got.

#56 인증 글 불러오는 기능 추가
  data/src/main/java/com/whyranoid/data/Post/PostDataSource.kt
  data/src/main/java/com/whyranoid/data/constant/FieldId.kt
  data/src/main/java/com/whyranoid/data/model/PostResponse.kt
  presentation/src/main/java/com/whyranoid/presentation/community/PostAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/util/BindingAdapters.kt
  presentation/src/main/res/layout/item_recruit_post.xml
  presentation/src/main/res/layout/item_running_post.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수

#55 운동 기록 선택 후 인증글 작성 구현 및 uid Flow에서 한번만 받아오도록 수정
  data/src/main/java/com/whyranoid/data/account/AccountDataSource.kt
  data/src/main/java/com/whyranoid/data/account/AccountDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/AccountRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/di/PostModule.kt
  data/src/main/java/com/whyranoid/data/post/PostDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/post/PostRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/AccountRepository.kt
  domain/src/main/java/com/whyranoid/domain/repository/PostRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CreatePostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CreateRunningPostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetUidUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/JoinGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/StartRunningUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/base/BaseActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/base/BaseFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CreateRunningPostFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/SelectRunningHistoryFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CommunityRunningHistoryAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CreateRunningPostFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CreateRunningPostViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/RunningHistoryItemListener.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/SelectRunningHistoryFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/SelectRunningHistoryViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/CalendarDayBinder.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunningHistoryAdapter.kt
  presentation/src/main/res/layout/fragment_create_running_post.xml
  presentation/src/main/res/menu/community_create_running_post_menu.xml
  presentation/src/main/res/menu/community_go_to_create_running_post_menu.xml
  presentation/src/main/res/menu/community_select_running_history_menu.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 승민

#57 러닝 화면 개선 및 러닝 종료 화면 구현
  data/src/main/java/com/whyranoid/data/account/RunningHistoryDao.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataBase.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSource.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSource.kt
  data/src/main/java/com/whyranoid/data/model/RunningHistoryEntity.kt
  data/src/main/java/com/whyranoid/data/running/RunnerDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/running/RunnerRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunningHistoryRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/SaveRunningHistoryUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CreateRunningPostViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/SelectRunningHistoryViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/model/RunningHistoryUiModel.kt
  presentation/src/main/java/com/whyranoid/presentation/running/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningDataManager.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningPosition.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningWorker.kt
  presentation/src/main/java/com/whyranoid/presentation/running/TrackingMode.kt
  presentation/src/main/java/com/whyranoid/presentation/runningfinish/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/runningfinish/RunningFinishFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningfinish/RunningFinishViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/util/Extensions.kt
  presentation/src/main/java/com/whyranoid/presentation/util/pxdp/PxDpUtil.kt
  presentation/src/main/res/layout/activity_running.xml
  presentation/src/main/res/layout/fragment_running_finish.xml
  presentation/src/main/res/layout/item_running_history.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 병희, 용한

#59 :bug: 마이런에서도 내 운동기록 화면 나오도록 수정
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CommunityRunningHistoryAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/myrun/MyRunViewModel.kt
  presentation/src/main/res/layout/fragment_my_run.xml
Labels: 리뷰요청, 승민

#61 본인 기기에 저장된 Uid를 기반으로 데이터를 불러오도록 수정
  domain/src/main/java/com/whyranoid/domain/usecase/CreateGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/CreateRecruitPostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyGroupListUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
  presentation/src/main/res/layout/fragment_group_detail.xml
Labels: 현수

#67 그룹 가입, 나가기 기능 구현, 내가 쓴 글 탭 구현, 게시글 삭제 구현 및 리팩토링 작업
  app/build.gradle
  build.gradle
  data/src/main/java/com/whyranoid/data/constant/FieldId.kt
  data/src/main/java/com/whyranoid/data/di/GroupModule.kt
  data/src/main/java/com/whyranoid/data/di/PostModule.kt
  data/src/main/java/com/whyranoid/data/group/GroupDataSource.kt
  data/src/main/java/com/whyranoid/data/group/GroupDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSource.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/model/GroupNotificationResponse.kt
  data/src/main/java/com/whyranoid/data/post/PostDataSource.kt
  data/src/main/java/com/whyranoid/data/post/PostDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/post/PostRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSource.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSourceImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/repository/PostRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/DeleteGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/ExitGroupUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyPostUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/MyGroupAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/PostAdapter.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/EditGroupFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/EditGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/util/Extensions.kt
  presentation/src/main/res/drawable/radius_background.xml
  presentation/src/main/res/layout/fragment_create_group.xml
  presentation/src/main/res/layout/fragment_edit_group.xml
  presentation/src/main/res/layout/my_finish_notification_item.xml
  presentation/src/main/res/layout/my_start_notification_item.xml
  presentation/src/main/res/layout/other_finish_notification_item.xml
  presentation/src/main/res/layout/other_start_notification_item.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 현수

#68 러닝 히스토리 아이템 UI 개선, 러닝 시작/종료 시 로딩 UI 추가
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/util/BindingAdapters.kt
  presentation/src/main/res/drawable/background_rounded.xml
  presentation/src/main/res/layout/activity_running.xml
  presentation/src/main/res/layout/item_running_history.xml
  presentation/src/main/res/layout/item_running_post.xml
  presentation/src/main/res/values/strings.xml
Labels: 리뷰요청, 병희

#69 러닝 엑티비티 백스택 관리, 뒤로가기 버튼 콜백 추가, 인증 글 쓰기 페이지 연결
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningWorker.kt
  presentation/src/main/java/com/whyranoid/presentation/runningfinish/RunningFinishFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartViewModel.kt
  presentation/src/main/res/layout/fragment_running_finish.xml
  presentation/src/main/res/navigation/navigation_graph.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 리뷰요청, 용한

#73 :recycle: GroupDataSourceImpl 함수 콜백 깊이 제거 리펙토링
  data/src/main/java/com/whyranoid/data/group/GroupDataSourceImpl.kt
Labels: 용한, 현수

#74 커뮤니티 탭 UI 일부 수정
  presentation/src/main/res/layout/fragment_community.xml
  presentation/src/main/res/layout/fragment_create_group.xml
  presentation/src/main/res/layout/fragment_edit_group.xml
  presentation/src/main/res/layout/fragment_group_detail.xml
  presentation/src/main/res/layout/item_running_post.xml
Labels: 리뷰요청, 현수

#76 러닝탭 관련 버그 수정
  presentation/src/main/java/com/whyranoid/presentation/running/RunningDataManager.kt
  presentation/src/main/java/com/whyranoid/presentation/runningfinish/RunningFinishFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/res/layout/fragment_running_finish.xml
  presentation/src/main/res/navigation/navigation_graph.xml
Labels: 리뷰요청, 용한

#78 shimmer 설정 변경, 메서드 컨벤션 맞추기, 운동 종료 알림 정렬 로직 변경
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
Labels: 리뷰요청, 현수

#82 앱을 삭제했다가 다시 깔거나 다른 디바이스에서 로그인할 때 정보가 유지되도록 수정
  data/src/main/java/com/whyranoid/data/account/RunningHistoryDao.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryRemoteDataSource.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryRemoteDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/account/RunningHistoryRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/model/RunningHistoryResponse.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunningHistoryRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/FinishRunningUseCase.kt
  signin/src/main/java/com/whyranoid/RestoreRunningHistoryDataUseCase.kt
  signin/src/main/java/com/whyranoid/SignInDataSource.kt
  signin/src/main/java/com/whyranoid/SignInDataSourceImpl.kt
  signin/src/main/java/com/whyranoid/SignInRepository.kt
  signin/src/main/java/com/whyranoid/SignInRepositoryImpl.kt
  signin/src/main/java/com/whyranoid/SignInViewModel.kt
  signin/src/main/java/com/whyranoid/signin/SignInActivity.kt
Labels: 리뷰요청, 승민

#83 RunningActivity 생명주기 관찰 옵저버 생성
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivity.kt
  presentation/src/main/java/com/whyranoid/presentation/running/RunningActivityObserver.kt
Labels: 리뷰요청, 용한

#84 복잡한 callback suspend하게 변경, PagingDataSource 개선
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/post/MyPostPagingDataSource.kt
  data/src/main/java/com/whyranoid/data/post/PostDataSource.kt
  data/src/main/java/com/whyranoid/data/post/PostDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/post/PostPagingDataSource.kt
  data/src/main/java/com/whyranoid/data/post/PostRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSource.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSourceImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/repository/PostRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyGroupListUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyPagingPostsUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetPagingPostsUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
Labels: 리뷰완료, 현수

#87 Shimmer관련 이슈 수정, 새로고침 기능 구현
  build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/res/layout/fragment_community_item.xml
Labels: 리뷰요청, 현수

#89 :recycle: 문자열 상수로 변경, 취소 가능한 서스펜드 변경
  data/src/main/java/com/whyranoid/data/constant/CollectionId.kt
  data/src/main/java/com/whyranoid/data/running/RunnerDataSourceImpl.kt
Labels: 리뷰요청, 용한

#90 컴포즈로 상단 스낵바 구현
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CreateRunningPostFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/compose/TopSnackBar.kt
  presentation/src/main/res/layout/fragment_create_running_post.xml
Labels: 리뷰요청, 현수

#93 [핫픽스] - 규칙 관련 이슈 해결
  domain/src/main/java/com/whyranoid/domain/model/Rule.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupViewModel.kt
Labels: 현수, 🌶️HotFix🌶️

#94 Data Layer에서 ViewModelScope를 사용하지 않도록 변경
  data/src/main/java/com/whyranoid/data/account/RunningHistoryLocalDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/di/CoroutineModule.kt
  data/src/main/java/com/whyranoid/data/di/DispatchersQualifiers.kt
  data/src/main/java/com/whyranoid/data/group/GroupDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/group/GroupRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/groupnotification/GroupNotificationDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/running/RunnerDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSource.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSourceImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyGroupListUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
Labels: 리뷰요청, 현수

#96 커뮤니티 탭 Ux 일부 개선
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/Event.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/runningpost/CreateRunningPostFragment.kt
  presentation/src/main/res/layout/fragment_community_item.xml
  presentation/src/main/res/layout/my_post_item.xml
  presentation/src/main/res/layout/post_item_loading.xml
Labels: 리뷰요청, 현수

#98 RulePicker 레이아웃 일부 수정
  presentation/src/main/java/com/whyranoid/presentation/compose/DropDownMenu.kt
Labels: 리뷰요청, 현수

#99 domain layer 테스트 코드 임시로 작성
  build.gradle
  domain/build.gradle
  domain/src/test/java/com/whyranoid/domain/useCase/GetGroupInfoUseCaseTest.kt
  domain/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: 리뷰요청, 현수

#100 달리는 사람의 수를 UiState로 관리하도록 변경
  data/src/main/java/com/whyranoid/data/running/RunnerDataSource.kt
  data/src/main/java/com/whyranoid/data/running/RunnerDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/running/RunnerRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunnerRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetRunnerCountUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/runningstart/RunningStartViewModel.kt
Labels: 리뷰요청, 용한, 현수

#101 GetMyGroupListUseCase() 관련 부분 Result, UiState처리 / 불필요한 코드 삭제 / Post 페이징 할 때 Result 처리하도록 변경
  data/src/main/java/com/whyranoid/data/post/PostDataSource.kt
  data/src/main/java/com/whyranoid/data/post/PostDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/post/PostPagingDataSource.kt
  data/src/main/java/com/whyranoid/data/post/PostRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSource.kt
  data/src/main/java/com/whyranoid/data/user/UserDataSourceImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/GroupRepository.kt
  domain/src/main/java/com/whyranoid/domain/repository/PostRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyGroupListUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetMyPostUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/GetPostsUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityItemFragment.kt
  presentation/src/main/java/com/whyranoid/presentation/community/CommunityViewModel.kt
Labels: 리뷰요청, 현수

#102 이벤트를 관리하는 SharedFlow -> EventFlow로 변경(Community)
  presentation/src/main/java/com/whyranoid/presentation/community/group/create/CreateGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/detail/GroupDetailViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/community/group/edit/EditGroupViewModel.kt
  presentation/src/main/java/com/whyranoid/presentation/util/EventFlow.kt
Labels: 현수
